### ISSUE TITLE
如何拿到socket.io的实例

### ISSUE THREAD

**Issue by jinyang1994** [whatwewant/dva-socket.io#3]
我想拿到socket.io创建的实例。目前看了一下代码，是没有办法拿到的

**Comment by whatwewant** [comment]
这个库的初衷是希望不从外部用socket.io的实例做一些不可预测的行为，造成bug或不可预测情况，避免导出用直接用emit/on等方法.

你可以说说为什么要拿到socket.io实例？可能给你提供建议.

**Comment by jinyang1994** [comment]
我的期望是这样的，在合适的时候才打开websocket连接，所以就需要使用open和close的方法。

**Comment by whatwewant** [comment]
Hi, 目前已支持获取到socket实例，或者更棒的方法是通过dispatch action安全使用socket进行open/close, 可升级版本0.0.6

目前还没有更新文档: 可先参考 @Elvin1993 的 PR: https://github.com/whatwewant/dva-socket.io/pull/5

**Comment by jinyang1994** [comment]
手动点赞👍

**Comment by murrayee** [comment]
在asyncs 里面  evaluate 的action 只会记住第一次dispatch的action
